title: "Designing Transparent Neural Networks"
description: "Generalized Linear and Additive Models are well-established interpretable approaches to supervised learning. This post connects these approaches to the building blocks of Neural Networks, and demonstrates that it's possible to design Neural Networks that are just as transparent."
date: 2021-03-04
heroImage: "/images/nam.png"
categories: ["transparency"]
